# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginpanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 389)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/h.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(1, 0, 42);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"    font: 75 bold 18pt \"Ubuntu\";\n"
"    color: rgb(199, 133, 0);\n"
"}\n"
"")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: rgb(1, 0, 42);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 60, 231, 251))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/img/h.png"))
        self.label.setObjectName("label")
        self.birframe = QtWidgets.QFrame(self.centralwidget)
        self.birframe.setGeometry(QtCore.QRect(10, 10, 551, 371))
        self.birframe.setStyleSheet("#birframe{\n"
"    background-color: rgb(87, 137, 139, 200);\n"
"    border: 1px solid white;\n"
"    border-radius: 10px;\n"
"}")
        self.birframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.birframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.birframe.setObjectName("birframe")
        self.ikiframe = QtWidgets.QFrame(self.birframe)
        self.ikiframe.setGeometry(QtCore.QRect(130, -204, 301, 191))
        self.ikiframe.setStyleSheet("#ikiframe{\n"
"    background-color: rgb(255, 255, 255, 140);\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"}")
        self.ikiframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ikiframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ikiframe.setObjectName("ikiframe")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.ikiframe)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/kullanıcı/img/user_male3-32.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.kads = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.kads.setStyleSheet("#kads{\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 bold 10pt \"Ubuntu\";\n"
"}")
        self.kads.setObjectName("kads")
        self.horizontalLayout.addWidget(self.kads)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.kad = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.kad.setMinimumSize(QtCore.QSize(0, 25))
        self.kad.setStyleSheet("#kad{\n"
"    background-color: rgb(255, 255, 255,  160);\n"
"    border: 1px;\n"
"    border-radius: 5px;\n"
"}")
        self.kad.setObjectName("kad")
        self.horizontalLayout.addWidget(self.kad)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/key/img/key-32.png"))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.kparolas = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.kparolas.setStyleSheet("#kparolas{\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 bold 10pt \"Ubuntu\";\n"
"}")
        self.kparolas.setObjectName("kparolas")
        self.horizontalLayout_2.addWidget(self.kparolas)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.kparola = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.kparola.setMinimumSize(QtCore.QSize(0, 25))
        self.kparola.setStyleSheet("#kparola{;\n"
"    background-color: rgb(255, 255, 255, 160);\n"
"    border: 1px;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.kparola.setEchoMode(QtWidgets.QLineEdit.Password)
        self.kparola.setObjectName("kparola")
        self.horizontalLayout_2.addWidget(self.kparola)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.log = QtWidgets.QPushButton(self.ikiframe)
        self.log.setGeometry(QtCore.QRect(110, 150, 90, 28))
        self.log.setStyleSheet("QPushButton#log{\n"
"    background-color: rgb(54, 145, 171);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton#log:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(54, 145, 171);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"}")
        self.log.setObjectName("log")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.log.clicked.connect(MainWindow.logincontrol) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HAS İDDAA LOGİN PANEL"))
        self.kads.setText(_translate("MainWindow", "Kullanıcı Adı    :"))
        self.kparolas.setText(_translate("MainWindow", "Kullanıcı Şifre :"))
        self.log.setText(_translate("MainWindow", "Giriş Yap"))
import icon_rc
